address feedback wip
andresfernandez89/app-futbol-ya pull request #1
Opened 2022-06-20 22:14 UTC by andresfernandez89

2022-07-04 23:45 UTC, VikoDroid requested changes

2022-07-04 23:45 UTC, VikoDroid commented on src/index.scss
> +}
Los fondos van como un atributo `background`  en el CSS, no como elemento `img`.

2022-07-04 23:45 UTC, VikoDroid commented on public/index.html
> +    <img class="mainBg" src="main-background.jpg" alt="fondo de pantalla" />
Los fondos van como un atributo background en el CSS, no como elemento img.

2022-07-04 23:45 UTC, VikoDroid commented on src/components/app/App.module.scss
> +    z-index: 99;
No hace falta usar `z-index`.

2022-07-04 23:45 UTC, VikoDroid commented on src/components/app/App.module.scss
> +    align-self: flex-end;
Por que esta prop? Al usar esto te fuerza a usar tambien `width: 100%`.

2022-07-04 23:45 UTC, VikoDroid commented on src/components/app/App.module.css
> +}
Creo que este archivo hay que borrarlo

2022-07-04 23:45 UTC, VikoDroid commented on src/components/app/App.module.css
> +  border-bottom: 0;
Esto para que es?

2022-07-05 01:40 UTC, andresfernandez89 commented on src/components/app/App.module.css
> +}
Si, este lo voy a borrar.

2022-07-07 23:44 UTC, andresfernandez89 commented
Correcciones hechas. Me quedo pendiente que no lo pude hacer andar en el file Navbar.module.scss, bloque de la linea 63, la pseudo-clase focus.

2022-07-13 02:32 UTC, VikoDroid approved these changes
Bien!

2022-07-13 03:13 UTC, andresfernandez89 commented
Tenes que mergear vos Jorjon, tengo la funcionalidad "Mergin is blocked"

2022-07-18 19:49 UTC, merged